site_name: HELIOS++ Documentation
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/3dgeo-heidelberg/helios/
docs_dir: docs
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides

plugins:
  - search
  - mkdoxy:
      projects:
        heliosAPI:
          src-dirs: ./src
          full-doc: true
          doxy-cfg:
            SHORT_NAMES: true
            FILE_PATTERNS: "*.h *.hpp *.hh *.hxx *.c *.cc *.cpp *.cxx"
            RECURSIVE: true
            EXTRACT_ALL: true
  - mkdocs-jupyter:
      execute: true
      allow_errors: false
      kernel_name: python3

extra_javascript:
  - javascript/readthedocs.js

nav:
  - Home: index.md
  - Notebooks:
      - Import Helios: notebooks/helios-import.ipynb
  - C++ API Documentation:
      - Links: heliosAPI/links.md
      - Classes:
          - Class List: heliosAPI/annotated.md
          - Class Index: heliosAPI/classes.md
          - Class Hierarchy: heliosAPI/hierarchy.md
          - Class Members: heliosAPI/class_members.md
          - Class Member Functions: heliosAPI/class_member_functions.md
          - Class Member Variables: heliosAPI/class_member_variables.md
          - Class Member Typedefs: heliosAPI/class_member_typedefs.md
          - Class Member Enumerations: heliosAPI/class_member_enums.md
      - Namespaces:
          - Namespace List: heliosAPI/namespaces.md
          - Namespace Members: heliosAPI/namespace_members.md
          - Namespace Member Functions: heliosAPI/namespace_member_functions.md
          - Namespace Member Variables: heliosAPI/namespace_member_variables.md
          - Namespace Member Typedefs: heliosAPI/namespace_member_typedefs.md
          - Namespace Member Enumerations: heliosAPI/namespace_member_enums.md
      - Functions: heliosAPI/functions.md
      - Variables: heliosAPI/variables.md
      - Macros: heliosAPI/macros.md
      - Files: heliosAPI/files.md
